### ISSUE TITLE
Why the requirement on webcrypto?

### ISSUE THREAD

**Issue by jackkleeman** [multiformats/js-multihashing-async#22]
It would be fairly simple to import native-crypto or a similar library that falls back on js libraries for crypto in the absence of webcrypto; in the meantime, js-ipfs doesn't work in a webworker in safari, and in other bad browsers.

**Comment by dignifiedquire** [comment]
If you want to do that, you can shim the global object appropriately. But we don't want to include these shims as they increase the bundle size very considerably.

**Comment by jackkleeman** [comment]
Ok true, why not use js libraries for hash functions though? Is the performance improvement worth the loss in browser support?

**Comment by dignifiedquire** [comment]
> Is the performance improvement worth the loss in browser support?

The combination of size increase + performance was worth for us yes. The majority of js-ipfs in the browser relies on webrtc to do real peer to peer connections in the browser, which restricts us to new browsers already in a lot of use cases. 

But it would be great to have a shim that one could just include in older browsers to offer support there. It shouldn't be too hard to implement one that just takes the js based implementations and emulates the same api.

**Comment by diasdavid** [comment]
> The combination of size increase + performance was worth for us yes.

Almost 10x perf improv. It is definitely valuable to have a way to use JS crypto libraries instead of WebCrypto, happy to accept a PR that brings that in.

**Comment by jackkleeman** [comment]
I have my own fork which uses the native-crypto package, which will use webcrypto when available and js libraries elsewhere. It might be overkill for this though, as we only use hashing functions.

https://github.com/duomarket/js-multihashing-async

Note this fork uses a native-crypto global when available, it's not a dependency, this is because in my use case native crypto is imported by a different browserify bundle.

**Comment by lidel** [comment]
FYSA WebCrypto in Chrome is available only in [secure contexts](https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#Which-origins-are-secure) and Firefox is also [planning to introduce the same restriction](https://bugzilla.mozilla.org/show_bug.cgi?id=1333140).

We should provide a better error message to address errors caused by insecure origin (PR #30).

**Comment by hugomrdias** [comment]
old issue gonna close this, feel free to reopen
