### ISSUE TITLE
Multihashing.functions is missing dbl-sha2-256

### ISSUE THREAD

**Issue by vmx** [multiformats/js-multihashing-async#25]
js-multihashing-async has its own set of functions that need to be updated if a new hash algorithm is added. For Bitcoin/Zcash support dbl-sha2-256 was added. That one needs to be added.

**Comment by diasdavid** [comment]
@vmx did you use multihashing for those two modules instead of multihashing-async?

**Comment by vmx** [comment]
Yes, I've used multihash (https://github.com/multiformats/js-multihash) for ipld-bitcoin and ipld-zcash.

**Comment by vmx** [comment]
@diasdavid: now I get what you mean. I've used hash.js directly. I guess I should use js-multihashing-async instead.
