### ISSUE TITLE
Using SPHINCS+ sha256-256f in IPLD Graph Data 

### ISSUE THREAD

**Issue by nothingismagick** [multiformats/js-multihashing-async#27]
I posted this question at [discuss](https://discuss.ipfs.io/t/using-sphincs-sha256-256f-in-ipld-graph-data/2501) and would like to contribute code in this library to enable this type of encryption in multiformats - and was directed here. This is a tracking issue that should be closed if my pull-request is merged or if the approach is inappropriate. Discussion is welcome!

**Comment by hugomrdias** [comment]
old issue gonna close this, feel free to reopen
