### ISSUE TITLE
SHAKE digest size

### ISSUE THREAD

**Issue by richardschneider** [multiformats/js-multihashing-async#28]
The shake-128 and shake-256 digests size are double what they should be.  From examining the [NIST test vectors](https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Secure-Hashing#sha3vsha3vss), shake-128 is 16 bytes (128 bits) and shake-256 is 32 bytes (256 bits).

**Comment by richardschneider** [comment]
@diasdavid or @vmx please grant me access to this repo and I'll add a PR for the issue.

**Comment by diasdavid** [comment]
@richardschneider added you to the JavaScript team in multiformats. Thank you :)

**Comment by richardschneider** [comment]
@diasdavid mea culpa, forgot to accept to the invitation.
