### ISSUE TITLE
The npm distribution is not transpiled to es5

### ISSUE THREAD

**Issue by rmisio** [multiformats/js-multihashing-async#32]
> The code published to npm that gets loaded on require is in fact a ES5 transpiled version with the right shims added. This means that you can require it and use with your favourite bundler without having to adjust asset management process.

This does not seem to be the case. When I look through the code in the `dist` folder, I do see a bunch of `let` statements in there.

A manifestation of the problem for me is that building an app made via create-react-app fails with the following error:

```
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/multihashing-async/src/index.js:28 
```

I believe the minifier is expecting transpiled ES5 code.

As a work-around, I could just bring the `js-multihashing-async` into my own codebase so that my transpiler will transpile it, but this is not ideal and not the accepted best practice. Furthermore, I'm not even using the lib directly. It's a dependency of `libp2p-crypto`.

**Comment by hugomrdias** [comment]
old issue gonna close this, feel free to reopen
